export const products = [
	{
		id: '3r0938343',
		slug: '',
		img: '/photos/sofa.png',
		model: 'Velvet Midnight Natural Sofa',
		price: 1200,
		type: 'sofa',
	},
	{
		id: '56potgj5p6o',
		slug: '',
		img: '/photos/sofa1.png',
		model: 'Modern Furniture',
		price: 1340,
		type: 'sofa',
	},
	{
		id: '45tt4ef',
		slug: '',
		img: '/photos/chair.png',
		model: 'Modern Furniture Set',
		price: 1100,
		type: 'sofa',
	},
	{
		id: '34534r4r',
		slug: '',
		img: '/photos/chair2.png',
		model: 'Furniture Sofa  Set',
		price: 1250,
		type: 'sofa',
	},

	{
		id: '34543frf',
		slug: '',
		img: '/photos/table.png',
		model: '',
		price: 1120,
		type: 'table',
	},
	{
		id: 'jopjoyij95',
		slug: '',
		img: '/photos/table2.png',
		model: 'Modern Table Collection',
		price: 1200,
		type: 'table',
	},
	{
		id: 'oreig8g9',
		slug: '',
		img: '/photos/table3.png',
		model: 'Luxury Gold Accent Table',
		price: 1250,
		type: 'table',
	},
	{
		id: 'ldfhoifhg909',
		slug: '',
		img: '/photos/table4.png',
		model: 'Classic Table Collection',
		price: 1000,
		type: 'table',
	},

	{
		id: 'flkjklkl3424',
		slug: '',
		img: '/photos/lamp.png',
		model: 'Losh Design Lamp',
		price: 1100,
		type: 'lamp',
	},
	{
		id: '45t43oin45',
		slug: '',
		img: '/photos/lamp2.png',
		model: 'Ofula Glass Lamp',
		price: 900,
		type: 'lamp',
	},
	{
		id: 'fgljkfnerkgner5',
		slug: '',
		img: '/photos/lamp3.png',
		model: 'Best Bedroom Lamp',
		price: 800,
		type: 'lamp',
	},
	{
		id: '33233334rf4f3',
		slug: '',
		img: '/photos/lamp4.png',
		model: 'Furniture & Dining Sets',
		price: 1200,
		type: 'lamp',
	},
];

export const categories = [
	{
		discount: 25,
		label: 'Kreslolar',
		textButton: 'Shop Now',
		img: '/photos/Rectangle.jpg',
	},
	{
		discount: 40,
		label: 'Divanlar',
		textButton: 'Shop Now',
		img: '/photos/Rectangle1.jpg',
	},
	{
		discount: 35,
		label: 'Maktab bellari',
		textButton: 'Shop Now',
		img: '/photos/table.jpeg',
	},
	{
		discount: 12,
		label: 'Spalniy mebellar',
		img: '/photos/spalniy.jpeg',
		textButton: 'Shop Now',
	},
];
